name: Build and Push Redis with Cell Docker Image

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ] # Trigger on version tags
  pull_request:
    branches: [ main ] # Trigger on PRs (build only)

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Push permission for GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request' # Login only on push
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Use GITHUB_TOKEN

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/redis-with-cell # GHCR image name

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3 # Setup QEMU for multi-arch

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }} # Push only on push
          tags: ${{ steps.meta.outputs.tags }} # Use generated tags
          labels: ${{ steps.meta.outputs.labels }} # Use generated labels
          platforms: linux/amd64,linux/arm64 # Target platforms
          cache-from: type=gha
          cache-to: type=gha,mode=max # Build cache